#!/usr/bin/env python3.5

import sys

from datetime import datetime, timedelta
# daily [开始日期] [截止日期（不包含）] | xargs -L1 sh -c '命令 $0'

try:
    date_format = "%Y-%m-%d"
    start_date  = datetime.strptime(sys.argv[1], date_format)
    end_date    = datetime.strptime(sys.argv[2], date_format)
except:
    date_format = "%Y%m%d"
    start_date  = datetime.strptime(sys.argv[1], date_format)
    end_date    = datetime.strptime(sys.argv[2], date_format)

today = start_date
while today < end_date:
    print(today.strftime(date_format))
    today += timedelta(days=1)
